[2016-08-14 16:01:02] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /login" (from "http://galleryfoto/")" at C:\OpenServer\domains\GalleryFoto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /login\" (from \"http://galleryfoto/\") at C:\\OpenServer\\domains\\GalleryFoto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:48)"} []
[2016-08-14 16:02:51] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /login" (from "http://galleryfoto/")" at C:\OpenServer\domains\GalleryFoto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /login\" (from \"http://galleryfoto/\") at C:\\OpenServer\\domains\\GalleryFoto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:48)"} []
[2016-08-14 17:46:10] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /auth"" at C:\OpenServer\domains\GalleryFoto\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /auth\" at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:48)"} []
[2016-08-14 17:47:05] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /auth"" at C:\OpenServer\domains\GalleryFoto\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /auth\" at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:48)"} []
[2016-08-14 19:54:16] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /auth"" at C:\OpenServer\domains\GalleryFoto\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /auth\" at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:48)"} []
[2016-08-14 19:55:19] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /login" (from "http://galleryfoto/")" at C:\OpenServer\domains\GalleryFoto\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /login\" (from \"http://galleryfoto/\") at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:48)"} []
[2016-08-14 19:57:07] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /auth" (from "http://galleryfoto/")" at C:\OpenServer\domains\GalleryFoto\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /auth\" (from \"http://galleryfoto/\") at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:48)"} []
[2016-08-14 19:58:06] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /auth" (from "http://galleryfoto/")" at C:\OpenServer\domains\GalleryFoto\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /auth\" (from \"http://galleryfoto/\") at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:48)"} []
[2016-08-14 19:58:29] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /auth" (from "http://galleryfoto/")" at C:\OpenServer\domains\GalleryFoto\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /auth\" (from \"http://galleryfoto/\") at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:48)"} []
[2016-08-14 20:39:42] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-14 20:39:42] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-14 20:39:43] request.CRITICAL: Uncaught PHP Exception LogicException: "The controller must return a response (404 given)." at C:\OpenServer\domains\GalleryFoto\app\bootstrap.php.cache line 3245 {"exception":"[object] (LogicException(code: 0): The controller must return a response (404 given). at C:\\OpenServer\\domains\\GalleryFoto\\app\\bootstrap.php.cache:3245)"} []
[2016-08-14 22:43:10] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-14 22:43:10] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-14 22:43:13] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "SerializerBuilder" from namespace "Gallery\GalleryBundle\Controller". Did you forget a "use" statement for another namespace?" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 31 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"SerializerBuilder\" from namespace \"Gallery\\GalleryBundle\\Controller\".\nDid you forget a \"use\" statement for another namespace? at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:31)"} []
[2016-08-14 22:51:19] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-14 22:51:19] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-14 22:51:22] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "SerializerBuilder" from namespace "Gallery\GalleryBundle\Controller". Did you forget a "use" statement for another namespace?" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 31 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"SerializerBuilder\" from namespace \"Gallery\\GalleryBundle\\Controller\".\nDid you forget a \"use\" statement for another namespace? at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:31)"} []
[2016-08-15 11:38:46] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 11:38:46] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 11:38:47] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Cannot use object of type Gallery\GalleryBundle\Entity\User as array" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 29 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Cannot use object of type Gallery\\GalleryBundle\\Entity\\User as array at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:29)"} []
[2016-08-15 11:45:53] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 11:45:53] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 11:45:54] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Cannot use object of type Gallery\GalleryBundle\Entity\User as array" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 29 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Cannot use object of type Gallery\\GalleryBundle\\Entity\\User as array at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:29)"} []
[2016-08-15 11:52:44] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 11:52:44] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 11:52:44] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function getResult() on array" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 23 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function getResult() on array at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:23)"} []
[2016-08-15 12:07:19] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 12:07:19] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 12:07:20] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Cannot use object of type Gallery\GalleryBundle\Entity\User as array" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 29 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Cannot use object of type Gallery\\GalleryBundle\\Entity\\User as array at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:29)"} []
[2016-08-15 12:07:58] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 12:07:58] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 12:07:59] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Cannot use object of type Gallery\GalleryBundle\Entity\User as array" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 29 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Cannot use object of type Gallery\\GalleryBundle\\Entity\\User as array at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:29)"} []
[2016-08-15 12:08:19] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 12:08:19] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 12:08:19] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Cannot use object of type Gallery\GalleryBundle\Entity\User as array" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 29 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Cannot use object of type Gallery\\GalleryBundle\\Entity\\User as array at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:29)"} []
[2016-08-15 12:10:46] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 12:10:46] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 12:10:46] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Cannot use object of type Gallery\GalleryBundle\Entity\User as array" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 26 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Cannot use object of type Gallery\\GalleryBundle\\Entity\\User as array at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:26)"} []
[2016-08-15 12:13:57] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 12:13:57] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 12:13:57] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Object of class Gallery\GalleryBundle\Entity\User could not be converted to string" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 30 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Object of class Gallery\\GalleryBundle\\Entity\\User could not be converted to string at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:30)"} []
[2016-08-15 12:14:25] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 12:14:25] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 12:14:26] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Object of class Gallery\GalleryBundle\Entity\User could not be converted to string" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 30 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Object of class Gallery\\GalleryBundle\\Entity\\User could not be converted to string at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:30)"} []
[2016-08-15 12:27:36] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 12:27:36] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 12:27:36] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Parse Error: syntax error, unexpected '=>' (T_DOUBLE_ARROW)" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 36 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Parse Error: syntax error, unexpected '=>' (T_DOUBLE_ARROW) at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:36)"} []
[2016-08-15 12:27:46] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 12:27:46] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 12:27:46] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Parse Error: syntax error, unexpected '=>' (T_DOUBLE_ARROW)" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 36 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Parse Error: syntax error, unexpected '=>' (T_DOUBLE_ARROW) at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:36)"} []
[2016-08-15 12:28:38] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 12:28:38] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 12:28:38] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Parse Error: syntax error, unexpected 'if' (T_IF)" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 33 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Parse Error: syntax error, unexpected 'if' (T_IF) at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:33)"} []
[2016-08-15 12:28:58] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 12:28:58] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 12:28:58] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Parse Error: syntax error, unexpected 'if' (T_IF)" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 33 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Parse Error: syntax error, unexpected 'if' (T_IF) at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:33)"} []
[2016-08-15 12:40:49] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 12:40:49] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 12:40:49] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function Getpassword() on array" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 31 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function Getpassword() on array at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:31)"} []
[2016-08-15 12:46:23] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 12:46:23] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 12:46:23] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedFunctionException: "Attempted to call function "password" from namespace "Gallery\GalleryBundle\Controller"." at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 31 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedFunctionException(code: 0): Attempted to call function \"password\" from namespace \"Gallery\\GalleryBundle\\Controller\". at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:31)"} []
[2016-08-15 13:15:20] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 13:15:20] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 13:15:20] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Parse Error: syntax error, unexpected 'tok' (T_STRING)" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 42 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Parse Error: syntax error, unexpected 'tok' (T_STRING) at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:42)"} []
[2016-08-15 13:15:40] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 13:15:40] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 13:15:40] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Parse Error: syntax error, unexpected 'tok' (T_STRING)" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 42 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Parse Error: syntax error, unexpected 'tok' (T_STRING) at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:42)"} []
[2016-08-15 13:19:00] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 13:19:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 13:19:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function setToken() on null" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 41 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function setToken() on null at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:41)"} []
[2016-08-15 13:19:18] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 13:19:18] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 13:19:19] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function setToken() on array" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 41 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function setToken() on array at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:41)"} []
[2016-08-15 13:19:39] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 13:19:39] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 13:19:40] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "setToken" of class "Doctrine\ORM\Query"." at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 41 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"setToken\" of class \"Doctrine\\ORM\\Query\". at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:41)"} []
[2016-08-15 13:22:46] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 13:22:46] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 13:22:46] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function setToken() on null" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 45 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function setToken() on null at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:45)"} []
[2016-08-15 13:23:46] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 13:23:46] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 13:23:46] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function setToken() on array" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 45 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function setToken() on array at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:45)"} []
[2016-08-15 13:24:32] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 13:24:32] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 13:24:32] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function setToken() on array" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 43 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function setToken() on array at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:43)"} []
[2016-08-15 13:27:30] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 13:27:30] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 13:27:30] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "EntityManager#remove() expects parameter 1 to be an entity object, array given." at C:\OpenServer\domains\GalleryFoto\vendor\doctrine\orm\lib\Doctrine\ORM\ORMInvalidArgumentException.php line 169 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException(code: 0): EntityManager#remove() expects parameter 1 to be an entity object, array given. at C:\\OpenServer\\domains\\GalleryFoto\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\ORMInvalidArgumentException.php:169)"} []
[2016-08-15 13:30:43] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 13:30:43] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 13:30:43] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function setToken() on array" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 43 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function setToken() on array at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:43)"} []
[2016-08-15 13:33:01] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 13:33:01] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 13:33:01] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function setToken() on array" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 44 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function setToken() on array at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:44)"} []
[2016-08-15 13:34:50] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 13:34:50] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 13:34:50] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMException: "The identifier id is missing for a query of Gallery\GalleryBundle\Entity\User" at C:\OpenServer\domains\GalleryFoto\vendor\doctrine\orm\lib\Doctrine\ORM\ORMException.php line 259 {"exception":"[object] (Doctrine\\ORM\\ORMException(code: 0): The identifier id is missing for a query of Gallery\\GalleryBundle\\Entity\\User at C:\\OpenServer\\domains\\GalleryFoto\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\ORMException.php:259)"} []
[2016-08-15 13:35:39] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 13:35:39] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 13:35:39] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function setToken() on array" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 44 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function setToken() on array at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:44)"} []
[2016-08-15 13:35:54] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 13:35:54] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 13:35:55] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function setToken() on array" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 44 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function setToken() on array at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:44)"} []
[2016-08-15 13:38:55] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 13:38:55] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 13:38:55] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function setToken() on array" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 44 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function setToken() on array at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:44)"} []
[2016-08-15 14:27:51] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 14:27:51] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 14:27:51] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function settoken() on array" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 44 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function settoken() on array at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:44)"} []
[2016-08-15 14:28:10] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 14:28:11] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 14:28:11] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function setToken() on array" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 44 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function setToken() on array at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:44)"} []
[2016-08-15 14:28:24] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 14:28:24] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 14:28:24] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function setToken() on array" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 44 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function setToken() on array at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:44)"} []
[2016-08-15 14:30:47] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 14:30:47] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 14:30:47] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function setToken() on null" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\AuthController.php line 44 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function setToken() on null at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\AuthController.php:44)"} []
[2016-08-15 19:00:28] request.INFO: Matched route "gallery_gallery_auth". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\AuthController::indexAction","_route":"gallery_gallery_auth"},"request_uri":"http://galleryfoto/web/auth"} []
[2016-08-15 19:00:28] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-15 19:00:28] request.CRITICAL: Uncaught PHP Exception UnexpectedValueException: "The Response content must be a string or object implementing __toString(), "array" given." at C:\OpenServer\domains\GalleryFoto\app\bootstrap.php.cache line 1536 {"exception":"[object] (UnexpectedValueException(code: 0): The Response content must be a string or object implementing __toString(), \"array\" given. at C:\\OpenServer\\domains\\GalleryFoto\\app\\bootstrap.php.cache:1536)"} []
[2016-08-15 21:18:43] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /preview" (from "http://galleryfoto/")" at C:\OpenServer\domains\GalleryFoto\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /preview\" (from \"http://galleryfoto/\") at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:53)"} []
[2016-08-15 21:19:58] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /preview" (from "http://galleryfoto/")" at C:\OpenServer\domains\GalleryFoto\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /preview\" (from \"http://galleryfoto/\") at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:53)"} []
[2016-08-15 21:20:14] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /preview"" at C:\OpenServer\domains\GalleryFoto\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /preview\" at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:53)"} []
[2016-08-15 21:36:01] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /preview" (from "http://galleryfoto/")" at C:\OpenServer\domains\GalleryFoto\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /preview\" (from \"http://galleryfoto/\") at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:53)"} []
[2016-08-15 21:36:47] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /preview" (from "http://galleryfoto/")" at C:\OpenServer\domains\GalleryFoto\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /preview\" (from \"http://galleryfoto/\") at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:53)"} []
[2016-08-15 21:37:42] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /preview"" at C:\OpenServer\domains\GalleryFoto\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /preview\" at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:53)"} []
[2016-08-15 21:38:17] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /preview"" at C:\OpenServer\domains\GalleryFoto\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /preview\" at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:53)"} []
[2016-08-15 21:38:40] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /preview" (from "http://galleryfoto/")" at C:\OpenServer\domains\GalleryFoto\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /preview\" (from \"http://galleryfoto/\") at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:53)"} []
[2016-08-15 21:39:57] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /preview" (from "http://galleryfoto/")" at C:\OpenServer\domains\GalleryFoto\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /preview\" (from \"http://galleryfoto/\") at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:53)"} []
[2016-08-15 21:40:53] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /preview"" at C:\OpenServer\domains\GalleryFoto\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /preview\" at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:53)"} []
[2016-08-15 21:42:56] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /preview"" at C:\OpenServer\domains\GalleryFoto\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /preview\" at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:53)"} []
[2016-08-15 21:44:06] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /preview"" at C:\OpenServer\domains\GalleryFoto\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /preview\" at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:53)"} []
[2016-08-15 21:46:13] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /preview"" at C:\OpenServer\domains\GalleryFoto\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /preview\" at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:53)"} []
[2016-08-15 23:26:49] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /bundle/upload.php" (from "http://galleryfoto/")" at C:\OpenServer\domains\GalleryFoto\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /bundle/upload.php\" (from \"http://galleryfoto/\") at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:58)"} []
[2016-08-15 23:30:59] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /bundle/upload.php" (from "http://galleryfoto/")" at C:\OpenServer\domains\GalleryFoto\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /bundle/upload.php\" (from \"http://galleryfoto/\") at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:58)"} []
[2016-08-16 00:51:06] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /load" (from "http://galleryfoto/")" at C:\OpenServer\domains\GalleryFoto\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /load\" (from \"http://galleryfoto/\") at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:58)"} []
[2016-08-16 00:51:43] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /%D0%B4%D1%89%D1%84%D0%B2"" at C:\OpenServer\domains\GalleryFoto\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /%D0%B4%D1%89%D1%84%D0%B2\" at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:58)"} []
[2016-08-16 00:51:48] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /load"" at C:\OpenServer\domains\GalleryFoto\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /load\" at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:58)"} []
[2016-08-16 00:54:57] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /load" (from "http://galleryfoto/")" at C:\OpenServer\domains\GalleryFoto\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /load\" (from \"http://galleryfoto/\") at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:58)"} []
[2016-08-16 00:57:22] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /load" (from "http://galleryfoto/")" at C:\OpenServer\domains\GalleryFoto\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /load\" (from \"http://galleryfoto/\") at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:58)"} []
[2016-08-16 00:57:42] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /load" (from "http://galleryfoto/")" at C:\OpenServer\domains\GalleryFoto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /load\" (from \"http://galleryfoto/\") at C:\\OpenServer\\domains\\GalleryFoto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:58)"} []
[2016-08-16 01:00:59] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /load" (from "http://galleryfoto/")" at C:\OpenServer\domains\GalleryFoto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /load\" (from \"http://galleryfoto/\") at C:\\OpenServer\\domains\\GalleryFoto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:58)"} []
[2016-08-16 01:06:14] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /load" (from "http://galleryfoto/")" at C:\OpenServer\domains\GalleryFoto\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /load\" (from \"http://galleryfoto/\") at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:58)"} []
[2016-08-16 01:06:28] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /load" (from "http://galleryfoto/")" at C:\OpenServer\domains\GalleryFoto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /load\" (from \"http://galleryfoto/\") at C:\\OpenServer\\domains\\GalleryFoto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:58)"} []
[2016-08-16 01:13:11] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /load" (from "http://galleryfoto/")" at C:\OpenServer\domains\GalleryFoto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /load\" (from \"http://galleryfoto/\") at C:\\OpenServer\\domains\\GalleryFoto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:58)"} []
[2016-08-16 01:13:34] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /load" (from "http://galleryfoto/")" at C:\OpenServer\domains\GalleryFoto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /load\" (from \"http://galleryfoto/\") at C:\\OpenServer\\domains\\GalleryFoto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:58)"} []
[2016-08-16 01:13:53] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /load" (from "http://galleryfoto/")" at C:\OpenServer\domains\GalleryFoto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /load\" (from \"http://galleryfoto/\") at C:\\OpenServer\\domains\\GalleryFoto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:58)"} []
[2016-08-16 01:14:43] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /load" (from "http://galleryfoto/")" at C:\OpenServer\domains\GalleryFoto\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /load\" (from \"http://galleryfoto/\") at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:58)"} []
[2016-08-16 01:16:16] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /load"" at C:\OpenServer\domains\GalleryFoto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /load\" at C:\\OpenServer\\domains\\GalleryFoto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\GalleryFoto\\app\\cache\\prod\\appProdUrlMatcher.php:58)"} []
[2016-08-16 01:41:50] request.INFO: Matched route "gallery_gallery_load". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\LoadController::indexAction","_route":"gallery_gallery_load"},"request_uri":"http://galleryfoto/web/load"} []
[2016-08-16 01:41:50] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-16 01:41:50] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "getParameter" of class "Symfony\Component\HttpFoundation\Request"." at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\LoadController.php line 15 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"getParameter\" of class \"Symfony\\Component\\HttpFoundation\\Request\". at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\LoadController.php:15)"} []
[2016-08-16 01:43:30] request.INFO: Matched route "gallery_gallery_load". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\LoadController::indexAction","_route":"gallery_gallery_load"},"request_uri":"http://galleryfoto/web/load"} []
[2016-08-16 01:43:30] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-16 01:43:30] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function getParameter() on null" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\LoadController.php line 15 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function getParameter() on null at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\LoadController.php:15)"} []
[2016-08-16 01:43:52] request.INFO: Matched route "gallery_gallery_load". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\LoadController::indexAction","_route":"gallery_gallery_load"},"request_uri":"http://galleryfoto/web/load"} []
[2016-08-16 01:43:52] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-16 01:43:52] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function getParameter() on null" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\LoadController.php line 15 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function getParameter() on null at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\LoadController.php:15)"} []
[2016-08-16 01:44:13] request.INFO: Matched route "gallery_gallery_load". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\LoadController::indexAction","_route":"gallery_gallery_load"},"request_uri":"http://galleryfoto/web/load"} []
[2016-08-16 01:44:13] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-16 01:44:13] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function getParameter() on null" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\LoadController.php line 15 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function getParameter() on null at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\LoadController.php:15)"} []
[2016-08-16 01:44:31] request.INFO: Matched route "gallery_gallery_load". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\LoadController::indexAction","_route":"gallery_gallery_load"},"request_uri":"http://galleryfoto/web/load"} []
[2016-08-16 01:44:31] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-16 01:44:31] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function getParameter() on null" at C:\OpenServer\domains\GalleryFoto\src\Gallery\GalleryBundle\Controller\LoadController.php line 15 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function getParameter() on null at C:\\OpenServer\\domains\\GalleryFoto\\src\\Gallery\\GalleryBundle\\Controller\\LoadController.php:15)"} []
[2016-08-16 01:57:43] request.INFO: Matched route "gallery_gallery_load". {"route_parameters":{"_controller":"Gallery\\GalleryBundle\\Controller\\LoadController::indexAction","_route":"gallery_gallery_load"},"request_uri":"http://galleryfoto/web/load"} []
[2016-08-16 01:57:44] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2016-08-16 01:57:44] request.CRITICAL: Uncaught PHP Exception UnexpectedValueException: "The Response content must be a string or object implementing __toString(), "array" given." at C:\OpenServer\domains\GalleryFoto\app\bootstrap.php.cache line 1536 {"exception":"[object] (UnexpectedValueException(code: 0): The Response content must be a string or object implementing __toString(), \"array\" given. at C:\\OpenServer\\domains\\GalleryFoto\\app\\bootstrap.php.cache:1536)"} []
[2016-11-03 10:48:59] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /api"" at C:\server\OpenServer\domains\open\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api\" at C:\\server\\OpenServer\\domains\\open\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\server\\OpenServer\\domains\\open\\app\\cache\\prod\\appProdUrlMatcher.php:63)"} []
[2016-11-03 20:18:16] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api/creatamount?comment=sss&date=2016-11-03&id_categor=Milk&sum=12"} []
[2016-11-03 20:18:16] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 20:18:16] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 20:18:16] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, "2016-11-03 20:18:16", "2016-11-03 20:18:16"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, \"2016-11-03 20:18:16\", \"2016-11-03 20:18:16\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 20:18:17] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 20:18:50] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api/creatamount?comment=sss&date=2016-11-03&id_categor=Milk&sum=12"} []
[2016-11-03 20:18:50] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 20:18:50] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 20:18:50] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, "2016-11-03 20:18:50", "2016-11-03 20:18:50"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, \"2016-11-03 20:18:50\", \"2016-11-03 20:18:50\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 20:18:50] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 20:19:05] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api/creatamount"} []
[2016-11-03 20:19:05] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 20:19:05] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 20:19:05] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, "2016-11-03 20:19:05", "2016-11-03 20:19:05"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, \"2016-11-03 20:19:05\", \"2016-11-03 20:19:05\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 20:19:06] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 20:20:27] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api/creatamount"} []
[2016-11-03 20:20:27] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 20:20:27] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 20:20:27] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, "2016-11-03 20:20:27", "2016-11-03 20:20:27"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, \"2016-11-03 20:20:27\", \"2016-11-03 20:20:27\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 20:20:27] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 20:21:29] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api/creatamount?comment=sss&date=2016-11-03&id_categor=Milk&sum=12"} []
[2016-11-03 20:21:29] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 20:21:29] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 20:21:30] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, "2016-11-03 20:21:29", "2016-11-03 20:21:29"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, \"2016-11-03 20:21:29\", \"2016-11-03 20:21:29\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 20:21:30] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 20:21:41] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api/creatamount"} []
[2016-11-03 20:21:41] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 20:21:41] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 20:21:41] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, "2016-11-03 20:21:41", "2016-11-03 20:21:41"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, \"2016-11-03 20:21:41\", \"2016-11-03 20:21:41\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 20:21:41] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 20:21:47] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api/creatamount"} []
[2016-11-03 20:21:47] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 20:21:47] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 20:21:47] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, "2016-11-03 20:21:47", "2016-11-03 20:21:47"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, \"2016-11-03 20:21:47\", \"2016-11-03 20:21:47\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 20:21:47] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 20:22:23] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api/"} []
[2016-11-03 20:22:23] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 20:22:23] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 20:22:23] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, "2016-11-03 20:22:23", "2016-11-03 20:22:23"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, \"2016-11-03 20:22:23\", \"2016-11-03 20:22:23\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 20:22:23] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 20:22:32] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /api/creatamount" (from "http://backend/public/")" at C:\OpenServer\domains\BackEnd\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/creatamount\" (from \"http://backend/public/\") at C:\\OpenServer\\domains\\BackEnd\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\BackEnd\\app\\cache\\prod\\appProdUrlMatcher.php:72)"} []
[2016-11-03 20:22:52] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api/?comment=sss&date=2016-11-03&id_categor=Milk&sum=12"} []
[2016-11-03 20:22:53] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 20:22:53] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 20:22:53] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, "2016-11-03 20:22:53", "2016-11-03 20:22:53"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, \"2016-11-03 20:22:53\", \"2016-11-03 20:22:53\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 20:22:53] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 20:25:51] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /api/creatamount" (from "http://backend/public/")" at C:\OpenServer\domains\BackEnd\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /api/creatamount\" (from \"http://backend/public/\") at C:\\OpenServer\\domains\\BackEnd\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\BackEnd\\app\\cache\\prod\\appProdUrlMatcher.php:72)"} []
[2016-11-03 20:26:18] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api/"} []
[2016-11-03 20:26:18] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 20:26:18] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 20:26:19] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, "2016-11-03 20:26:19", "2016-11-03 20:26:19"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, \"2016-11-03 20:26:19\", \"2016-11-03 20:26:19\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 20:26:19] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 20:26:22] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api/"} []
[2016-11-03 20:26:22] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 20:26:22] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 20:26:22] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, "2016-11-03 20:26:22", "2016-11-03 20:26:22"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, \"2016-11-03 20:26:22\", \"2016-11-03 20:26:22\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 20:26:22] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 20:27:39] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api/"} []
[2016-11-03 20:27:39] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 20:27:39] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 20:27:39] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, "2016-11-03 20:27:39", "2016-11-03 20:27:39"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, \"2016-11-03 20:27:39\", \"2016-11-03 20:27:39\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 20:27:39] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 20:28:00] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api/creatamount"} []
[2016-11-03 20:28:00] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 20:28:00] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 20:28:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, "2016-11-03 20:28:00", "2016-11-03 20:28:00"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, \"2016-11-03 20:28:00\", \"2016-11-03 20:28:00\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 20:28:00] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 20:29:17] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api/creatamount"} []
[2016-11-03 20:29:17] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 20:29:17] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 20:29:17] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, "2016-11-03 20:29:17", "2016-11-03 20:29:17"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, \"2016-11-03 20:29:17\", \"2016-11-03 20:29:17\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 20:29:17] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 20:30:38] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api/creatamount"} []
[2016-11-03 20:30:38] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 20:30:38] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 20:30:38] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, "2016-11-03 20:30:38", "2016-11-03 20:30:38"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, \"2016-11-03 20:30:38\", \"2016-11-03 20:30:38\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 20:30:38] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 20:30:49] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api/creatamount"} []
[2016-11-03 20:30:49] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 20:30:49] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 20:30:49] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, "2016-11-03 20:30:49", "2016-11-03 20:30:49"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, \"2016-11-03 20:30:49\", \"2016-11-03 20:30:49\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 20:30:49] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 20:43:24] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api/creatamount"} []
[2016-11-03 20:43:24] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 20:43:24] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 20:43:24] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, "2016-11-03 20:43:24", "2016-11-03 20:43:24"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, \"2016-11-03 20:43:24\", \"2016-11-03 20:43:24\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 20:43:24] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 20:47:02] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api/creatamount"} []
[2016-11-03 20:47:02] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 20:47:02] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 20:47:02] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, "123", "Milk", null, "2016-11-03", "2016-11-03 20:47:02", "2016-11-03 20:47:02"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, \"123\", \"Milk\", null, \"2016-11-03\", \"2016-11-03 20:47:02\", \"2016-11-03 20:47:02\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 20:47:02] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 20:47:02] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api/creatamount"} []
[2016-11-03 20:47:02] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 20:47:02] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 20:47:02] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, "123", "Milk", null, "2016-11-03", "2016-11-03 20:47:02", "2016-11-03 20:47:02"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, \"123\", \"Milk\", null, \"2016-11-03\", \"2016-11-03 20:47:02\", \"2016-11-03 20:47:02\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 20:47:02] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 20:49:51] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/creatamount"} []
[2016-11-03 20:49:51] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 20:49:51] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 20:49:51] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, "2016-11-03 20:49:51", "2016-11-03 20:49:51"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, \"2016-11-03 20:49:51\", \"2016-11-03 20:49:51\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 20:49:52] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 20:50:21] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/creatamount"} []
[2016-11-03 20:50:21] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 20:50:21] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 20:50:21] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, "2016-11-03 20:50:21", "2016-11-03 20:50:21"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, \"2016-11-03 20:50:21\", \"2016-11-03 20:50:21\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 20:50:21] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 20:53:42] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/creatamount"} []
[2016-11-03 20:53:42] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 20:53:42] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 20:53:42] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, "2016-11-03 20:53:42", "2016-11-03 20:53:42"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, \"2016-11-03 20:53:42\", \"2016-11-03 20:53:42\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 20:53:42] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 20:55:39] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /creatamount"" at C:\OpenServer\domains\BackEnd\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /creatamount\" at C:\\OpenServer\\domains\\BackEnd\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\BackEnd\\app\\cache\\prod\\appProdUrlMatcher.php:39)"} []
[2016-11-03 20:55:46] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/"} []
[2016-11-03 20:55:46] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 20:55:46] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 20:55:46] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, "2016-11-03 20:55:46", "2016-11-03 20:55:46"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, \"2016-11-03 20:55:46\", \"2016-11-03 20:55:46\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 20:55:46] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 21:01:50] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /creatamount" (from "http://backend/public/")" at C:\OpenServer\domains\BackEnd\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /creatamount\" (from \"http://backend/public/\") at C:\\OpenServer\\domains\\BackEnd\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\BackEnd\\app\\cache\\prod\\appProdUrlMatcher.php:39)"} []
[2016-11-03 21:04:55] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /api/creatamount" (from "http://backend/public/")" at C:\OpenServer\domains\BackEnd\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /api/creatamount\" (from \"http://backend/public/\") at C:\\OpenServer\\domains\\BackEnd\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\BackEnd\\app\\cache\\prod\\appProdUrlMatcher.php:39)"} []
[2016-11-03 21:04:55] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /api/creatamount" (from "http://backend/public/")" at C:\OpenServer\domains\BackEnd\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /api/creatamount\" (from \"http://backend/public/\") at C:\\OpenServer\\domains\\BackEnd\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\BackEnd\\app\\cache\\prod\\appProdUrlMatcher.php:39)"} []
[2016-11-03 21:05:33] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /api/" (from "http://backend/public/")" at C:\OpenServer\domains\BackEnd\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /api/\" (from \"http://backend/public/\") at C:\\OpenServer\\domains\\BackEnd\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\BackEnd\\app\\cache\\prod\\appProdUrlMatcher.php:39)"} []
[2016-11-03 21:05:43] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /api" (from "http://backend/public/")" at C:\OpenServer\domains\BackEnd\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /api\" (from \"http://backend/public/\") at C:\\OpenServer\\domains\\BackEnd\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\BackEnd\\app\\cache\\prod\\appProdUrlMatcher.php:39)"} []
[2016-11-03 21:05:50] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/"} []
[2016-11-03 21:05:50] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 21:05:50] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 21:05:50] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, "2016-11-03 21:05:50", "2016-11-03 21:05:50"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, \"2016-11-03 21:05:50\", \"2016-11-03 21:05:50\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 21:05:50] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 21:05:56] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /api/"" at C:\OpenServer\domains\BackEnd\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/\" at C:\\OpenServer\\domains\\BackEnd\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\BackEnd\\app\\cache\\prod\\appProdUrlMatcher.php:39)"} []
[2016-11-03 21:10:00] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api/creatamount"} []
[2016-11-03 21:10:00] security.INFO: Basic authentication Authorization header found for user. {"username":"admin"} []
[2016-11-03 21:10:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params ["admin", null, null, null, null, "2016-11-03 21:10:00", "2016-11-03 21:10:00"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'sum' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [\"admin\", null, null, null, null, \"2016-11-03 21:10:00\", \"2016-11-03 21:10:00\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'sum' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'sum' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'sum' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 21:10:00] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 21:26:03] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api/creatamount"} []
[2016-11-03 21:26:03] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 21:26:03] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 21:26:03] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params ["admin", "123", "Milk", null, "2016-11-03", "2016-11-03 21:26:03", "2016-11-03 21:26:03"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [\"admin\", \"123\", \"Milk\", null, \"2016-11-03\", \"2016-11-03 21:26:03\", \"2016-11-03 21:26:03\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 21:26:04] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 21:26:03] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api/creatamount"} []
[2016-11-03 21:26:04] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 21:26:04] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 21:26:04] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params ["admin", "123", "Milk", null, "2016-11-03", "2016-11-03 21:26:04", "2016-11-03 21:26:04"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [\"admin\", \"123\", \"Milk\", null, \"2016-11-03\", \"2016-11-03 21:26:04\", \"2016-11-03 21:26:04\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 21:26:04] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 21:35:05] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api/creatamount"} []
[2016-11-03 21:35:06] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 21:35:06] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 21:35:06] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params ["admin", "123", "Milk", null, "2016-11-03", "2016-11-03 21:35:06", "2016-11-03 21:35:06"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [\"admin\", \"123\", \"Milk\", null, \"2016-11-03\", \"2016-11-03 21:35:06\", \"2016-11-03 21:35:06\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 21:35:06] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 21:35:05] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api/creatamount"} []
[2016-11-03 21:35:06] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 21:35:06] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 21:35:06] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params ["admin", "123", "Milk", null, "2016-11-03", "2016-11-03 21:35:06", "2016-11-03 21:35:06"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [\"admin\", \"123\", \"Milk\", null, \"2016-11-03\", \"2016-11-03 21:35:06\", \"2016-11-03 21:35:06\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 21:35:06] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 21:41:53] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api/creatamount"} []
[2016-11-03 21:41:53] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 21:41:53] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 21:41:53] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params ["admin", "123", "Milk", null, "2016-11-03", "2016-11-03 21:41:53", "2016-11-03 21:41:53"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [\"admin\", \"123\", \"Milk\", null, \"2016-11-03\", \"2016-11-03 21:41:53\", \"2016-11-03 21:41:53\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 21:41:53] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 21:41:53] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api/creatamount"} []
[2016-11-03 21:41:53] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 21:41:53] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 21:41:53] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params ["admin", "123", "Milk", null, "2016-11-03", "2016-11-03 21:41:53", "2016-11-03 21:41:53"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [\"admin\", \"123\", \"Milk\", null, \"2016-11-03\", \"2016-11-03 21:41:53\", \"2016-11-03 21:41:53\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 21:41:53] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 22:03:36] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api/creatamount"} []
[2016-11-03 22:03:36] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 22:03:36] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 22:03:36] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params ["admin", "123", "Milk", null, "2016-11-03", "2016-11-03 22:03:36", "2016-11-03 22:03:36"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [\"admin\", \"123\", \"Milk\", null, \"2016-11-03\", \"2016-11-03 22:03:36\", \"2016-11-03 22:03:36\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 22:03:36] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 22:05:57] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api/creatamount"} []
[2016-11-03 22:05:57] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 22:05:57] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 22:05:57] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params ["admin", "123", "Milk", null, "2016-11-03", "2016-11-03 22:05:57", "2016-11-03 22:05:57"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [\"admin\", \"123\", \"Milk\", null, \"2016-11-03\", \"2016-11-03 22:05:57\", \"2016-11-03 22:05:57\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 22:05:57] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-03 22:06:33] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api/creatamount"} []
[2016-11-03 22:06:33] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-03 22:06:33] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-03 22:06:33] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params ["admin", "123", "Milk", null, "2016-11-03", "2016-11-03 22:06:33", "2016-11-03 22:06:33"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [\"admin\", \"123\", \"Milk\", null, \"2016-11-03\", \"2016-11-03 22:06:33\", \"2016-11-03 22:06:33\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comments' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-03 22:06:34] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-04 19:01:41] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at C:\OpenServer\domains\BackEnd\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at C:\\OpenServer\\domains\\BackEnd\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\BackEnd\\app\\cache\\prod\\appProdUrlMatcher.php:47)"} []
[2016-11-04 19:07:14] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at C:\OpenServer\domains\BackEnd\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at C:\\OpenServer\\domains\\BackEnd\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\BackEnd\\app\\cache\\prod\\appProdUrlMatcher.php:47)"} []
[2016-11-04 19:07:26] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at C:\OpenServer\domains\BackEnd\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at C:\\OpenServer\\domains\\BackEnd\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\BackEnd\\app\\cache\\prod\\appProdUrlMatcher.php:47)"} []
[2016-11-04 19:08:03] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at C:\OpenServer\domains\BackEnd\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at C:\\OpenServer\\domains\\BackEnd\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\BackEnd\\app\\cache\\prod\\appProdUrlMatcher.php:47)"} []
[2016-11-05 10:36:39] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api"} []
[2016-11-05 10:36:39] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-05 10:36:39] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-05 10:36:39] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, "123", "Milk", "123", "2016-11-05", "2016-11-05 10:36:39", "2016-11-05 10:36:39"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, \"123\", \"Milk\", \"123\", \"2016-11-05\", \"2016-11-05 10:36:39\", \"2016-11-05 10:36:39\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-05 10:36:39] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-05 10:40:32] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api"} []
[2016-11-05 10:40:32] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-05 10:40:32] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-05 10:40:32] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, "123", "Milk", "123qwe", "2016-11-05", "2016-11-05 10:40:32", "2016-11-05 10:40:32"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, \"123\", \"Milk\", \"123qwe\", \"2016-11-05\", \"2016-11-05 10:40:32\", \"2016-11-05 10:40:32\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-05 10:40:32] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-05 10:51:01] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api"} []
[2016-11-05 10:51:01] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-05 10:51:01] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-05 10:51:01] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, "123", "Milk", "123qwe", "2016-11-05", "2016-11-05 10:51:01", "2016-11-05 10:51:01"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, \"123\", \"Milk\", \"123qwe\", \"2016-11-05\", \"2016-11-05 10:51:01\", \"2016-11-05 10:51:01\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-05 10:51:01] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-05 10:51:58] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api"} []
[2016-11-05 10:51:58] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-05 10:51:58] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-05 10:51:58] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, "2016-11-05 10:51:58", "2016-11-05 10:51:58"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, \"2016-11-05 10:51:58\", \"2016-11-05 10:51:58\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-05 10:51:58] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-05 10:54:05] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api"} []
[2016-11-05 10:54:05] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-05 10:54:05] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-05 10:54:05] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, "123", "Milk", "123qwe", "2016-11-05", "2016-11-05 10:54:05", "2016-11-05 10:54:05"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, \"123\", \"Milk\", \"123qwe\", \"2016-11-05\", \"2016-11-05 10:54:05\", \"2016-11-05 10:54:05\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-05 10:54:06] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-05 10:54:31] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api"} []
[2016-11-05 10:54:31] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-05 10:54:31] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-05 10:54:31] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, "123", "Milk", "123qwe", "2016-11-05", "2016-11-05 10:54:31", "2016-11-05 10:54:31"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, \"123\", \"Milk\", \"123qwe\", \"2016-11-05\", \"2016-11-05 10:54:31\", \"2016-11-05 10:54:31\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-05 10:54:31] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-05 10:56:51] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api"} []
[2016-11-05 10:56:51] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-05 10:56:51] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-05 10:56:51] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, "12", "transport", "weqq", "2016-11-05", "2016-11-05 10:56:51", "2016-11-05 10:56:51"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, \"12\", \"transport\", \"weqq\", \"2016-11-05\", \"2016-11-05 10:56:51\", \"2016-11-05 10:56:51\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-05 10:56:51] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-05 10:57:26] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api"} []
[2016-11-05 10:57:26] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-05 10:57:26] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-05 10:57:27] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, "12", "transport", "weqq", "2016-11-05", "2016-11-05 10:57:27", "2016-11-05 10:57:27"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, \"12\", \"transport\", \"weqq\", \"2016-11-05\", \"2016-11-05 10:57:27\", \"2016-11-05 10:57:27\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_name' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-05 10:57:27] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-05 13:13:09] request.INFO: Matched route "back_end_back_end_creatamount". {"route_parameters":{"_controller":"BackEnd\\BackEndBundle\\Controller\\CreatAmountController::indexAction","_route":"back_end_back_end_creatamount"},"request_uri":"http://backend/web/api?comments=123&date=2016-11-04&id_categor=&sum=123"} []
[2016-11-05 13:13:09] security.DEBUG: Read existing security token from the session. {"key":"_security_default"} []
[2016-11-05 13:13:09] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2016-11-05 13:13:09] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params ["admin", null, null, null, null, "2016-11-05 13:13:09", "2016-11-05 13:13:09"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'sum' cannot be null" at C:\OpenServer\domains\BackEnd\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO Amount (user_name, sum, id_categor, comments, date, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [\"admin\", null, null, null, null, \"2016-11-05 13:13:09\", \"2016-11-05 13:13:09\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'sum' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'sum' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'sum' cannot be null at C:\\OpenServer\\domains\\BackEnd\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []
[2016-11-05 13:13:09] security.DEBUG: Stored the security token in the session. {"key":"_security_default"} []
[2016-11-07 11:21:46] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Compile Error: Cannot redeclare class BackEnd\BackEndBundle\Controller\CreatAmountController" at C:\OpenServer\domains\BackEnd\src\BackEnd\BackEndBundle\Controller\LoginController.php line 32 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: Cannot redeclare class BackEnd\\BackEndBundle\\Controller\\CreatAmountController at C:\\OpenServer\\domains\\BackEnd\\src\\BackEnd\\BackEndBundle\\Controller\\LoginController.php:32)"} []
[2016-11-07 11:21:55] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Compile Error: Cannot redeclare class BackEnd\BackEndBundle\Controller\CreatAmountController" at C:\OpenServer\domains\BackEnd\src\BackEnd\BackEndBundle\Controller\LoginController.php line 32 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: Cannot redeclare class BackEnd\\BackEndBundle\\Controller\\CreatAmountController at C:\\OpenServer\\domains\\BackEnd\\src\\BackEnd\\BackEndBundle\\Controller\\LoginController.php:32)"} []
[2016-11-07 11:22:03] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Compile Error: Cannot redeclare class BackEnd\BackEndBundle\Controller\CreatAmountController" at C:\OpenServer\domains\BackEnd\src\BackEnd\BackEndBundle\Controller\LoginController.php line 32 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: Cannot redeclare class BackEnd\\BackEndBundle\\Controller\\CreatAmountController at C:\\OpenServer\\domains\\BackEnd\\src\\BackEnd\\BackEndBundle\\Controller\\LoginController.php:32)"} []
[2016-11-07 11:24:24] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Compile Error: Cannot redeclare class BackEnd\BackEndBundle\Controller\CreatAmountController" at C:\OpenServer\domains\BackEnd\src\BackEnd\BackEndBundle\Controller\LoginController.php line 32 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: Cannot redeclare class BackEnd\\BackEndBundle\\Controller\\CreatAmountController at C:\\OpenServer\\domains\\BackEnd\\src\\BackEnd\\BackEndBundle\\Controller\\LoginController.php:32)"} []
[2016-11-09 21:19:01] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /api/date" (from "http://backend/public/")" at C:\OpenServer\domains\BackEnd\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/date\" (from \"http://backend/public/\") at C:\\OpenServer\\domains\\BackEnd\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\BackEnd\\app\\cache\\prod\\appProdUrlMatcher.php:52)"} []
[2016-11-09 21:20:27] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /api/date" (from "http://backend/public/")" at C:\OpenServer\domains\BackEnd\app\cache\prod\classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /api/date\" (from \"http://backend/public/\") at C:\\OpenServer\\domains\\BackEnd\\app\\cache\\prod\\classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\OpenServer\\domains\\BackEnd\\app\\cache\\prod\\appProdUrlMatcher.php:52)"} []
